// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: PreLobby.proto

package PreLobby

import (
	Enum "github.com/zhanglifan/leaf_server/src/proto/Enum"
	Struct "github.com/zhanglifan/leaf_server/src/proto/Struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 请求： 登陆
type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    Enum.EPlatformType     `protobuf:"varint,1,opt,name=PlatformID,proto3,enum=Enum.EPlatformType" json:"PlatformID,omitempty"` // 平台 ID
	AccountID     string                 `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`                            // 账号 ID
	AccountName   string                 `protobuf:"bytes,3,opt,name=AccountName,proto3" json:"AccountName,omitempty"`                        // 账号名称
	JobNumber     string                 `protobuf:"bytes,4,opt,name=JobNumber,proto3" json:"JobNumber,omitempty"`                            // 工号
	AuthSecret    string                 `protobuf:"bytes,5,opt,name=AuthSecret,proto3" json:"AuthSecret,omitempty"`                          // 授权秘钥(steam授权后, 服务端生成)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_PreLobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetPlatformID() Enum.EPlatformType {
	if x != nil {
		return x.PlatformID
	}
	return Enum.EPlatformType(0)
}

func (x *ReqLogin) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *ReqLogin) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *ReqLogin) GetJobNumber() string {
	if x != nil {
		return x.JobNumber
	}
	return ""
}

func (x *ReqLogin) GetAuthSecret() string {
	if x != nil {
		return x.AuthSecret
	}
	return ""
}

// 反馈： 玩家角色信息
type RspRoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleUID       int64                  `protobuf:"varint,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`  // 角色 UID
	RoleName      string                 `protobuf:"bytes,2,opt,name=RoleName,proto3" json:"RoleName,omitempty"` // 角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspRoleInfo) Reset() {
	*x = RspRoleInfo{}
	mi := &file_PreLobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspRoleInfo) ProtoMessage() {}

func (x *RspRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspRoleInfo.ProtoReflect.Descriptor instead.
func (*RspRoleInfo) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{1}
}

func (x *RspRoleInfo) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

func (x *RspRoleInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// 请求： 创建角色
type ReqCreateRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"` // 角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqCreateRole) Reset() {
	*x = ReqCreateRole{}
	mi := &file_PreLobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateRole) ProtoMessage() {}

func (x *ReqCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateRole.ProtoReflect.Descriptor instead.
func (*ReqCreateRole) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{2}
}

func (x *ReqCreateRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// 反馈： 创建角色结果
type RspCreateRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`  // 是否成功
	RoleName      string                 `protobuf:"bytes,2,opt,name=RoleName,proto3" json:"RoleName,omitempty"` // 角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspCreateRole) Reset() {
	*x = RspCreateRole{}
	mi := &file_PreLobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspCreateRole) ProtoMessage() {}

func (x *RspCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspCreateRole.ProtoReflect.Descriptor instead.
func (*RspCreateRole) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{3}
}

func (x *RspCreateRole) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *RspCreateRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// 请求：进入大厅
type ReqEnterLobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqEnterLobby) Reset() {
	*x = ReqEnterLobby{}
	mi := &file_PreLobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqEnterLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEnterLobby) ProtoMessage() {}

func (x *ReqEnterLobby) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEnterLobby.ProtoReflect.Descriptor instead.
func (*ReqEnterLobby) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{4}
}

// 数据：玩家数据
type PlayerBaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleLevel     int32                  `protobuf:"varint,1,opt,name=RoleLevel,proto3" json:"RoleLevel,omitempty"`       // 角色等级
	RoleName      string                 `protobuf:"bytes,2,opt,name=RoleName,proto3" json:"RoleName,omitempty"`          // 角色名称
	HeroData      *Struct.HeroData       `protobuf:"bytes,3,opt,name=HeroData,proto3" json:"HeroData,omitempty"`          // 英雄数据
	OnlineTime    int32                  `protobuf:"varint,100,opt,name=OnlineTime,proto3" json:"OnlineTime,omitempty"`   // 玩家登录时间
	OfflineTime   int32                  `protobuf:"varint,101,opt,name=OfflineTime,proto3" json:"OfflineTime,omitempty"` // 玩家离线时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBaseInfo) Reset() {
	*x = PlayerBaseInfo{}
	mi := &file_PreLobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBaseInfo) ProtoMessage() {}

func (x *PlayerBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBaseInfo.ProtoReflect.Descriptor instead.
func (*PlayerBaseInfo) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerBaseInfo) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *PlayerBaseInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *PlayerBaseInfo) GetHeroData() *Struct.HeroData {
	if x != nil {
		return x.HeroData
	}
	return nil
}

func (x *PlayerBaseInfo) GetOnlineTime() int32 {
	if x != nil {
		return x.OnlineTime
	}
	return 0
}

func (x *PlayerBaseInfo) GetOfflineTime() int32 {
	if x != nil {
		return x.OfflineTime
	}
	return 0
}

// 反馈：进入大厅
type RspEnterLobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerInfo    *PlayerBaseInfo        `protobuf:"bytes,1,opt,name=PlayerInfo,proto3" json:"PlayerInfo,omitempty"` // 玩家数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspEnterLobby) Reset() {
	*x = RspEnterLobby{}
	mi := &file_PreLobby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspEnterLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspEnterLobby) ProtoMessage() {}

func (x *RspEnterLobby) ProtoReflect() protoreflect.Message {
	mi := &file_PreLobby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspEnterLobby.ProtoReflect.Descriptor instead.
func (*RspEnterLobby) Descriptor() ([]byte, []int) {
	return file_PreLobby_proto_rawDescGZIP(), []int{6}
}

func (x *RspEnterLobby) GetPlayerInfo() *PlayerBaseInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

var File_PreLobby_proto protoreflect.FileDescriptor

const file_PreLobby_proto_rawDesc = "" +
	"\n" +
	"\x0ePreLobby.proto\x12\bPreLobby\x1a\fStruct.proto\x1a\n" +
	"Enum.proto\"\xbd\x01\n" +
	"\bReqLogin\x123\n" +
	"\n" +
	"PlatformID\x18\x01 \x01(\x0e2\x13.Enum.EPlatformTypeR\n" +
	"PlatformID\x12\x1c\n" +
	"\tAccountID\x18\x02 \x01(\tR\tAccountID\x12 \n" +
	"\vAccountName\x18\x03 \x01(\tR\vAccountName\x12\x1c\n" +
	"\tJobNumber\x18\x04 \x01(\tR\tJobNumber\x12\x1e\n" +
	"\n" +
	"AuthSecret\x18\x05 \x01(\tR\n" +
	"AuthSecret\"C\n" +
	"\vRspRoleInfo\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\x03R\aRoleUID\x12\x1a\n" +
	"\bRoleName\x18\x02 \x01(\tR\bRoleName\"+\n" +
	"\rReqCreateRole\x12\x1a\n" +
	"\bRoleName\x18\x01 \x01(\tR\bRoleName\"E\n" +
	"\rRspCreateRole\x12\x18\n" +
	"\aSucceed\x18\x01 \x01(\bR\aSucceed\x12\x1a\n" +
	"\bRoleName\x18\x02 \x01(\tR\bRoleName\"\x0f\n" +
	"\rReqEnterLobby\"\xba\x01\n" +
	"\x0ePlayerBaseInfo\x12\x1c\n" +
	"\tRoleLevel\x18\x01 \x01(\x05R\tRoleLevel\x12\x1a\n" +
	"\bRoleName\x18\x02 \x01(\tR\bRoleName\x12,\n" +
	"\bHeroData\x18\x03 \x01(\v2\x10.Struct.HeroDataR\bHeroData\x12\x1e\n" +
	"\n" +
	"OnlineTime\x18d \x01(\x05R\n" +
	"OnlineTime\x12 \n" +
	"\vOfflineTime\x18e \x01(\x05R\vOfflineTime\"I\n" +
	"\rRspEnterLobby\x128\n" +
	"\n" +
	"PlayerInfo\x18\x01 \x01(\v2\x18.PreLobby.PlayerBaseInfoR\n" +
	"PlayerInfoB6Z4github.com/zhanglifan/leaf_server/src/proto/PreLobbyb\x06proto3"

var (
	file_PreLobby_proto_rawDescOnce sync.Once
	file_PreLobby_proto_rawDescData []byte
)

func file_PreLobby_proto_rawDescGZIP() []byte {
	file_PreLobby_proto_rawDescOnce.Do(func() {
		file_PreLobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PreLobby_proto_rawDesc), len(file_PreLobby_proto_rawDesc)))
	})
	return file_PreLobby_proto_rawDescData
}

var file_PreLobby_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_PreLobby_proto_goTypes = []any{
	(*ReqLogin)(nil),        // 0: PreLobby.ReqLogin
	(*RspRoleInfo)(nil),     // 1: PreLobby.RspRoleInfo
	(*ReqCreateRole)(nil),   // 2: PreLobby.ReqCreateRole
	(*RspCreateRole)(nil),   // 3: PreLobby.RspCreateRole
	(*ReqEnterLobby)(nil),   // 4: PreLobby.ReqEnterLobby
	(*PlayerBaseInfo)(nil),  // 5: PreLobby.PlayerBaseInfo
	(*RspEnterLobby)(nil),   // 6: PreLobby.RspEnterLobby
	(Enum.EPlatformType)(0), // 7: Enum.EPlatformType
	(*Struct.HeroData)(nil), // 8: Struct.HeroData
}
var file_PreLobby_proto_depIdxs = []int32{
	7, // 0: PreLobby.ReqLogin.PlatformID:type_name -> Enum.EPlatformType
	8, // 1: PreLobby.PlayerBaseInfo.HeroData:type_name -> Struct.HeroData
	5, // 2: PreLobby.RspEnterLobby.PlayerInfo:type_name -> PreLobby.PlayerBaseInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_PreLobby_proto_init() }
func file_PreLobby_proto_init() {
	if File_PreLobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PreLobby_proto_rawDesc), len(file_PreLobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PreLobby_proto_goTypes,
		DependencyIndexes: file_PreLobby_proto_depIdxs,
		MessageInfos:      file_PreLobby_proto_msgTypes,
	}.Build()
	File_PreLobby_proto = out.File
	file_PreLobby_proto_goTypes = nil
	file_PreLobby_proto_depIdxs = nil
}
