// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Base.proto

package Base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
type BaseMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgName       string                 `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"` // 消息名称
	MsgBody       []byte                 `protobuf:"bytes,2,opt,name=MsgBody,proto3" json:"MsgBody,omitempty"` // 消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseMsg) Reset() {
	*x = BaseMsg{}
	mi := &file_Base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMsg) ProtoMessage() {}

func (x *BaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_Base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMsg.ProtoReflect.Descriptor instead.
func (*BaseMsg) Descriptor() ([]byte, []int) {
	return file_Base_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMsg) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *BaseMsg) GetMsgBody() []byte {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

// ------------------------------------------------------------------
// 心跳包
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_Base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_Base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_Base_proto_rawDescGZIP(), []int{1}
}

var File_Base_proto protoreflect.FileDescriptor

const file_Base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Base.proto\x12\x04Base\"=\n" +
	"\aBaseMsg\x12\x18\n" +
	"\aMsgName\x18\x01 \x01(\tR\aMsgName\x12\x18\n" +
	"\aMsgBody\x18\x02 \x01(\fR\aMsgBody\"\v\n" +
	"\tHeartbeatB2Z0github.com/zhanglifan/leaf_server/src/proto/Baseb\x06proto3"

var (
	file_Base_proto_rawDescOnce sync.Once
	file_Base_proto_rawDescData []byte
)

func file_Base_proto_rawDescGZIP() []byte {
	file_Base_proto_rawDescOnce.Do(func() {
		file_Base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Base_proto_rawDesc), len(file_Base_proto_rawDesc)))
	})
	return file_Base_proto_rawDescData
}

var file_Base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Base_proto_goTypes = []any{
	(*BaseMsg)(nil),   // 0: Base.BaseMsg
	(*Heartbeat)(nil), // 1: Base.Heartbeat
}
var file_Base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Base_proto_init() }
func file_Base_proto_init() {
	if File_Base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Base_proto_rawDesc), len(file_Base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Base_proto_goTypes,
		DependencyIndexes: file_Base_proto_depIdxs,
		MessageInfos:      file_Base_proto_msgTypes,
	}.Build()
	File_Base_proto = out.File
	file_Base_proto_goTypes = nil
	file_Base_proto_depIdxs = nil
}
