// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Struct.proto

package Struct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 数据：物品 （武器、防具、道具）
type ItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int32                  `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`       // 物品 ID
	ItemCount     int32                  `protobuf:"varint,2,opt,name=ItemCount,proto3" json:"ItemCount,omitempty"` // 物品数量
	ItemLevel     int32                  `protobuf:"varint,3,opt,name=ItemLevel,proto3" json:"ItemLevel,omitempty"` // 物品等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_Struct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_Struct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_Struct_proto_rawDescGZIP(), []int{0}
}

func (x *ItemData) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *ItemData) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *ItemData) GetItemLevel() int32 {
	if x != nil {
		return x.ItemLevel
	}
	return 0
}

var File_Struct_proto protoreflect.FileDescriptor

const file_Struct_proto_rawDesc = "" +
	"\n" +
	"\fStruct.proto\x12\x06Struct\"^\n" +
	"\bItemData\x12\x16\n" +
	"\x06ItemID\x18\x01 \x01(\x05R\x06ItemID\x12\x1c\n" +
	"\tItemCount\x18\x02 \x01(\x05R\tItemCount\x12\x1c\n" +
	"\tItemLevel\x18\x03 \x01(\x05R\tItemLevelB4Z2github.com/zhanglifan/leaf_server/src/proto/Structb\x06proto3"

var (
	file_Struct_proto_rawDescOnce sync.Once
	file_Struct_proto_rawDescData []byte
)

func file_Struct_proto_rawDescGZIP() []byte {
	file_Struct_proto_rawDescOnce.Do(func() {
		file_Struct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Struct_proto_rawDesc), len(file_Struct_proto_rawDesc)))
	})
	return file_Struct_proto_rawDescData
}

var file_Struct_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Struct_proto_goTypes = []any{
	(*ItemData)(nil), // 0: Struct.ItemData
}
var file_Struct_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Struct_proto_init() }
func file_Struct_proto_init() {
	if File_Struct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Struct_proto_rawDesc), len(file_Struct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Struct_proto_goTypes,
		DependencyIndexes: file_Struct_proto_depIdxs,
		MessageInfos:      file_Struct_proto_msgTypes,
	}.Build()
	File_Struct_proto = out.File
	file_Struct_proto_goTypes = nil
	file_Struct_proto_depIdxs = nil
}
