// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Enum.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 平台类型枚举
type EPlatformType int32

const (
	EPlatformType_PLATFORM_DEVELOP EPlatformType = 0 // 开发账号
)

// Enum value maps for EPlatformType.
var (
	EPlatformType_name = map[int32]string{
		0: "PLATFORM_DEVELOP",
	}
	EPlatformType_value = map[string]int32{
		"PLATFORM_DEVELOP": 0,
	}
)

func (x EPlatformType) Enum() *EPlatformType {
	p := new(EPlatformType)
	*p = x
	return p
}

func (x EPlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_Enum_proto_enumTypes[0].Descriptor()
}

func (EPlatformType) Type() protoreflect.EnumType {
	return &file_Enum_proto_enumTypes[0]
}

func (x EPlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPlatformType.Descriptor instead.
func (EPlatformType) EnumDescriptor() ([]byte, []int) {
	return file_Enum_proto_rawDescGZIP(), []int{0}
}

// ------------------------------------------------------------------
// 错误码枚举
type EErrorCode int32

const (
	EErrorCode_SUCCESS EErrorCode = 0 // 成功
	EErrorCode_FAILED  EErrorCode = 1 // 失败
)

// Enum value maps for EErrorCode.
var (
	EErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	EErrorCode_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x EErrorCode) Enum() *EErrorCode {
	p := new(EErrorCode)
	*p = x
	return p
}

func (x EErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_Enum_proto_enumTypes[1].Descriptor()
}

func (EErrorCode) Type() protoreflect.EnumType {
	return &file_Enum_proto_enumTypes[1]
}

func (x EErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EErrorCode.Descriptor instead.
func (EErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_Enum_proto_rawDescGZIP(), []int{1}
}

var File_Enum_proto protoreflect.FileDescriptor

const file_Enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Enum.proto\x12\x04Enum*%\n" +
	"\rEPlatformType\x12\x14\n" +
	"\x10PLATFORM_DEVELOP\x10\x00*%\n" +
	"\n" +
	"EErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01B2Z0github.com/zhanglifan/leaf_server/src/proto/Enumb\x06proto3"

var (
	file_Enum_proto_rawDescOnce sync.Once
	file_Enum_proto_rawDescData []byte
)

func file_Enum_proto_rawDescGZIP() []byte {
	file_Enum_proto_rawDescOnce.Do(func() {
		file_Enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Enum_proto_rawDesc), len(file_Enum_proto_rawDesc)))
	})
	return file_Enum_proto_rawDescData
}

var file_Enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Enum_proto_goTypes = []any{
	(EPlatformType)(0), // 0: Enum.EPlatformType
	(EErrorCode)(0),    // 1: Enum.EErrorCode
}
var file_Enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Enum_proto_init() }
func file_Enum_proto_init() {
	if File_Enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Enum_proto_rawDesc), len(file_Enum_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Enum_proto_goTypes,
		DependencyIndexes: file_Enum_proto_depIdxs,
		EnumInfos:         file_Enum_proto_enumTypes,
	}.Build()
	File_Enum_proto = out.File
	file_Enum_proto_goTypes = nil
	file_Enum_proto_depIdxs = nil
}
