// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Enum.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 平台类型
type EPlatformType int32

const (
	EPlatformType_PLATFORM_NONE  EPlatformType = 0
	EPlatformType_PLATFORM_STEAM EPlatformType = 1 // Steam 平台
)

// Enum value maps for EPlatformType.
var (
	EPlatformType_name = map[int32]string{
		0: "PLATFORM_NONE",
		1: "PLATFORM_STEAM",
	}
	EPlatformType_value = map[string]int32{
		"PLATFORM_NONE":  0,
		"PLATFORM_STEAM": 1,
	}
)

func (x EPlatformType) Enum() *EPlatformType {
	p := new(EPlatformType)
	*p = x
	return p
}

func (x EPlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_Enum_proto_enumTypes[0].Descriptor()
}

func (EPlatformType) Type() protoreflect.EnumType {
	return &file_Enum_proto_enumTypes[0]
}

func (x EPlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPlatformType.Descriptor instead.
func (EPlatformType) EnumDescriptor() ([]byte, []int) {
	return file_Enum_proto_rawDescGZIP(), []int{0}
}

// 物品类型
type EGoodsType int32

const (
	EGoodsType_NONE      EGoodsType = 0
	EGoodsType_Weapon    EGoodsType = 1 // 武器
	EGoodsType_Equipment EGoodsType = 2 // 防具
)

// Enum value maps for EGoodsType.
var (
	EGoodsType_name = map[int32]string{
		0: "NONE",
		1: "Weapon",
		2: "Equipment",
	}
	EGoodsType_value = map[string]int32{
		"NONE":      0,
		"Weapon":    1,
		"Equipment": 2,
	}
)

func (x EGoodsType) Enum() *EGoodsType {
	p := new(EGoodsType)
	*p = x
	return p
}

func (x EGoodsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGoodsType) Descriptor() protoreflect.EnumDescriptor {
	return file_Enum_proto_enumTypes[1].Descriptor()
}

func (EGoodsType) Type() protoreflect.EnumType {
	return &file_Enum_proto_enumTypes[1]
}

func (x EGoodsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EGoodsType.Descriptor instead.
func (EGoodsType) EnumDescriptor() ([]byte, []int) {
	return file_Enum_proto_rawDescGZIP(), []int{1}
}

type EPlayerUI int32

const (
	EPlayerUI_UI_NONE   EPlayerUI = 0
	EPlayerUI_UI_LOBBY  EPlayerUI = 1 // 大厅
	EPlayerUI_UI_FRIEND EPlayerUI = 2 // 好友界面
)

// Enum value maps for EPlayerUI.
var (
	EPlayerUI_name = map[int32]string{
		0: "UI_NONE",
		1: "UI_LOBBY",
		2: "UI_FRIEND",
	}
	EPlayerUI_value = map[string]int32{
		"UI_NONE":   0,
		"UI_LOBBY":  1,
		"UI_FRIEND": 2,
	}
)

func (x EPlayerUI) Enum() *EPlayerUI {
	p := new(EPlayerUI)
	*p = x
	return p
}

func (x EPlayerUI) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EPlayerUI) Descriptor() protoreflect.EnumDescriptor {
	return file_Enum_proto_enumTypes[2].Descriptor()
}

func (EPlayerUI) Type() protoreflect.EnumType {
	return &file_Enum_proto_enumTypes[2]
}

func (x EPlayerUI) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EPlayerUI.Descriptor instead.
func (EPlayerUI) EnumDescriptor() ([]byte, []int) {
	return file_Enum_proto_rawDescGZIP(), []int{2}
}

var File_Enum_proto protoreflect.FileDescriptor

const file_Enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Enum.proto\x12\x04Enum*6\n" +
	"\rEPlatformType\x12\x11\n" +
	"\rPLATFORM_NONE\x10\x00\x12\x12\n" +
	"\x0ePLATFORM_STEAM\x10\x01*1\n" +
	"\n" +
	"EGoodsType\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06Weapon\x10\x01\x12\r\n" +
	"\tEquipment\x10\x02*5\n" +
	"\tEPlayerUI\x12\v\n" +
	"\aUI_NONE\x10\x00\x12\f\n" +
	"\bUI_LOBBY\x10\x01\x12\r\n" +
	"\tUI_FRIEND\x10\x02B2Z0github.com/zhanglifan/leaf_server/src/proto/Enumb\x06proto3"

var (
	file_Enum_proto_rawDescOnce sync.Once
	file_Enum_proto_rawDescData []byte
)

func file_Enum_proto_rawDescGZIP() []byte {
	file_Enum_proto_rawDescOnce.Do(func() {
		file_Enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Enum_proto_rawDesc), len(file_Enum_proto_rawDesc)))
	})
	return file_Enum_proto_rawDescData
}

var file_Enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Enum_proto_goTypes = []any{
	(EPlatformType)(0), // 0: Enum.EPlatformType
	(EGoodsType)(0),    // 1: Enum.EGoodsType
	(EPlayerUI)(0),     // 2: Enum.EPlayerUI
}
var file_Enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Enum_proto_init() }
func file_Enum_proto_init() {
	if File_Enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Enum_proto_rawDesc), len(file_Enum_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Enum_proto_goTypes,
		DependencyIndexes: file_Enum_proto_depIdxs,
		EnumInfos:         file_Enum_proto_enumTypes,
	}.Build()
	File_Enum_proto = out.File
	file_Enum_proto_goTypes = nil
	file_Enum_proto_depIdxs = nil
}
