// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: DBData.proto

package DBData

import (
	PreLobby "github.com/zhanglifan/leaf_server/src/proto/PreLobby"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// DS 信息
type DSData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int64       DSUID                   = 1;        // 服务器 UID
	ServerAddr    string `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"` // 服务器地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DSData) Reset() {
	*x = DSData{}
	mi := &file_DBData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSData) ProtoMessage() {}

func (x *DSData) ProtoReflect() protoreflect.Message {
	mi := &file_DBData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSData.ProtoReflect.Descriptor instead.
func (*DSData) Descriptor() ([]byte, []int) {
	return file_DBData_proto_rawDescGZIP(), []int{0}
}

func (x *DSData) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

// ------------------------------------------------------------------
// 玩家数据
// TODO: 之后拆分
type PlayerData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BaseInfo      *PreLobby.PlayerBaseInfo `protobuf:"bytes,1,opt,name=BaseInfo,proto3" json:"BaseInfo,omitempty"`    // 基础信息
	GameState     int32                    `protobuf:"varint,2,opt,name=GameState,proto3" json:"GameState,omitempty"` // 游戏状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	mi := &file_DBData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_DBData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_DBData_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerData) GetBaseInfo() *PreLobby.PlayerBaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *PlayerData) GetGameState() int32 {
	if x != nil {
		return x.GameState
	}
	return 0
}

var File_DBData_proto protoreflect.FileDescriptor

const file_DBData_proto_rawDesc = "" +
	"\n" +
	"\fDBData.proto\x12\x06DBData\x1a\x0ePreLobby.proto\"(\n" +
	"\x06DSData\x12\x1e\n" +
	"\n" +
	"ServerAddr\x18\x01 \x01(\tR\n" +
	"ServerAddr\"`\n" +
	"\n" +
	"PlayerData\x124\n" +
	"\bBaseInfo\x18\x01 \x01(\v2\x18.PreLobby.PlayerBaseInfoR\bBaseInfo\x12\x1c\n" +
	"\tGameState\x18\x02 \x01(\x05R\tGameStateB4Z2github.com/zhanglifan/leaf_server/src/proto/DBDatab\x06proto3"

var (
	file_DBData_proto_rawDescOnce sync.Once
	file_DBData_proto_rawDescData []byte
)

func file_DBData_proto_rawDescGZIP() []byte {
	file_DBData_proto_rawDescOnce.Do(func() {
		file_DBData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DBData_proto_rawDesc), len(file_DBData_proto_rawDesc)))
	})
	return file_DBData_proto_rawDescData
}

var file_DBData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DBData_proto_goTypes = []any{
	(*DSData)(nil),                  // 0: DBData.DSData
	(*PlayerData)(nil),              // 1: DBData.PlayerData
	(*PreLobby.PlayerBaseInfo)(nil), // 2: PreLobby.PlayerBaseInfo
}
var file_DBData_proto_depIdxs = []int32{
	2, // 0: DBData.PlayerData.BaseInfo:type_name -> PreLobby.PlayerBaseInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_DBData_proto_init() }
func file_DBData_proto_init() {
	if File_DBData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DBData_proto_rawDesc), len(file_DBData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DBData_proto_goTypes,
		DependencyIndexes: file_DBData_proto_depIdxs,
		MessageInfos:      file_DBData_proto_msgTypes,
	}.Build()
	File_DBData_proto = out.File
	file_DBData_proto_goTypes = nil
	file_DBData_proto_depIdxs = nil
}
