// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Friend.proto

package Friend

import (
	Enum "github.com/zhanglifan/leaf_server/src/proto/Enum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 请求: 好友服务测试
type ReqFriendTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqFriendTest) Reset() {
	*x = ReqFriendTest{}
	mi := &file_Friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFriendTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFriendTest) ProtoMessage() {}

func (x *ReqFriendTest) ProtoReflect() protoreflect.Message {
	mi := &file_Friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFriendTest.ProtoReflect.Descriptor instead.
func (*ReqFriendTest) Descriptor() ([]byte, []int) {
	return file_Friend_proto_rawDescGZIP(), []int{0}
}

// ------------------------------------------------------------------
// 响应: 好友服务测试
type RspFriendTest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码
	ErrorCode     Enum.EErrorCode `protobuf:"varint,1,opt,name=ErrorCode,proto3,enum=Enum.EErrorCode" json:"ErrorCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspFriendTest) Reset() {
	*x = RspFriendTest{}
	mi := &file_Friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspFriendTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspFriendTest) ProtoMessage() {}

func (x *RspFriendTest) ProtoReflect() protoreflect.Message {
	mi := &file_Friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspFriendTest.ProtoReflect.Descriptor instead.
func (*RspFriendTest) Descriptor() ([]byte, []int) {
	return file_Friend_proto_rawDescGZIP(), []int{1}
}

func (x *RspFriendTest) GetErrorCode() Enum.EErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return Enum.EErrorCode(0)
}

var File_Friend_proto protoreflect.FileDescriptor

const file_Friend_proto_rawDesc = "" +
	"\n" +
	"\fFriend.proto\x12\x06Friend\x1a\n" +
	"Enum.proto\"\x0f\n" +
	"\rReqFriendTest\"?\n" +
	"\rRspFriendTest\x12.\n" +
	"\tErrorCode\x18\x01 \x01(\x0e2\x10.Enum.EErrorCodeR\tErrorCodeB4Z2github.com/zhanglifan/leaf_server/src/proto/Friendb\x06proto3"

var (
	file_Friend_proto_rawDescOnce sync.Once
	file_Friend_proto_rawDescData []byte
)

func file_Friend_proto_rawDescGZIP() []byte {
	file_Friend_proto_rawDescOnce.Do(func() {
		file_Friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Friend_proto_rawDesc), len(file_Friend_proto_rawDesc)))
	})
	return file_Friend_proto_rawDescData
}

var file_Friend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Friend_proto_goTypes = []any{
	(*ReqFriendTest)(nil), // 0: Friend.ReqFriendTest
	(*RspFriendTest)(nil), // 1: Friend.RspFriendTest
	(Enum.EErrorCode)(0),  // 2: Enum.EErrorCode
}
var file_Friend_proto_depIdxs = []int32{
	2, // 0: Friend.RspFriendTest.ErrorCode:type_name -> Enum.EErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Friend_proto_init() }
func file_Friend_proto_init() {
	if File_Friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Friend_proto_rawDesc), len(file_Friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Friend_proto_goTypes,
		DependencyIndexes: file_Friend_proto_depIdxs,
		MessageInfos:      file_Friend_proto_msgTypes,
	}.Build()
	File_Friend_proto = out.File
	file_Friend_proto_goTypes = nil
	file_Friend_proto_depIdxs = nil
}
