// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: CFriend.proto

package CFriend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
type CFriendAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleUID       string                 `protobuf:"bytes,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`     // 玩家UID
	FriendUID     string                 `protobuf:"bytes,2,opt,name=FriendUID,proto3" json:"FriendUID,omitempty"` // 添加好友UID
	ListType      string                 `protobuf:"bytes,3,opt,name=ListType,proto3" json:"ListType,omitempty"`   // 添加列表类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CFriendAdd) Reset() {
	*x = CFriendAdd{}
	mi := &file_CFriend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CFriendAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CFriendAdd) ProtoMessage() {}

func (x *CFriendAdd) ProtoReflect() protoreflect.Message {
	mi := &file_CFriend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CFriendAdd.ProtoReflect.Descriptor instead.
func (*CFriendAdd) Descriptor() ([]byte, []int) {
	return file_CFriend_proto_rawDescGZIP(), []int{0}
}

func (x *CFriendAdd) GetRoleUID() string {
	if x != nil {
		return x.RoleUID
	}
	return ""
}

func (x *CFriendAdd) GetFriendUID() string {
	if x != nil {
		return x.FriendUID
	}
	return ""
}

func (x *CFriendAdd) GetListType() string {
	if x != nil {
		return x.ListType
	}
	return ""
}

var File_CFriend_proto protoreflect.FileDescriptor

const file_CFriend_proto_rawDesc = "" +
	"\n" +
	"\rCFriend.proto\x12\aCFriend\"`\n" +
	"\n" +
	"CFriendAdd\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\tR\aRoleUID\x12\x1c\n" +
	"\tFriendUID\x18\x02 \x01(\tR\tFriendUID\x12\x1a\n" +
	"\bListType\x18\x03 \x01(\tR\bListTypeB5Z3github.com/zhanglifan/leaf_server/src/proto/CFriendb\x06proto3"

var (
	file_CFriend_proto_rawDescOnce sync.Once
	file_CFriend_proto_rawDescData []byte
)

func file_CFriend_proto_rawDescGZIP() []byte {
	file_CFriend_proto_rawDescOnce.Do(func() {
		file_CFriend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CFriend_proto_rawDesc), len(file_CFriend_proto_rawDesc)))
	})
	return file_CFriend_proto_rawDescData
}

var file_CFriend_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CFriend_proto_goTypes = []any{
	(*CFriendAdd)(nil), // 0: CFriend.CFriendAdd
}
var file_CFriend_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CFriend_proto_init() }
func file_CFriend_proto_init() {
	if File_CFriend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CFriend_proto_rawDesc), len(file_CFriend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CFriend_proto_goTypes,
		DependencyIndexes: file_CFriend_proto_depIdxs,
		MessageInfos:      file_CFriend_proto_msgTypes,
	}.Build()
	File_CFriend_proto = out.File
	file_CFriend_proto_goTypes = nil
	file_CFriend_proto_depIdxs = nil
}
