// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Chat.proto

package Chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 公用结构
// ------------------------------------------------------------------
// 游戏状态
type EChatChannelType int32

const (
	EChatChannelType_EChatCH_None    EChatChannelType = 0 //
	EChatChannelType_EChatCH_World   EChatChannelType = 1 // 世界聊天
	EChatChannelType_EChatCH_Team    EChatChannelType = 2 // 小队聊天
	EChatChannelType_EChatCH_Private EChatChannelType = 3 // 私聊
)

// Enum value maps for EChatChannelType.
var (
	EChatChannelType_name = map[int32]string{
		0: "EChatCH_None",
		1: "EChatCH_World",
		2: "EChatCH_Team",
		3: "EChatCH_Private",
	}
	EChatChannelType_value = map[string]int32{
		"EChatCH_None":    0,
		"EChatCH_World":   1,
		"EChatCH_Team":    2,
		"EChatCH_Private": 3,
	}
)

func (x EChatChannelType) Enum() *EChatChannelType {
	p := new(EChatChannelType)
	*p = x
	return p
}

func (x EChatChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EChatChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_Chat_proto_enumTypes[0].Descriptor()
}

func (EChatChannelType) Type() protoreflect.EnumType {
	return &file_Chat_proto_enumTypes[0]
}

func (x EChatChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EChatChannelType.Descriptor instead.
func (EChatChannelType) EnumDescriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{0}
}

// 聊天消息的结构
type ChatMessageStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUID     int64                  `protobuf:"varint,1,opt,name=SenderUID,proto3" json:"SenderUID,omitempty"`     // 消息发送者
	SenderName    string                 `protobuf:"bytes,2,opt,name=SenderName,proto3" json:"SenderName,omitempty"`    // 发送者名字
	AccepterUID   int64                  `protobuf:"varint,3,opt,name=AccepterUID,proto3" json:"AccepterUID,omitempty"` // 消息接受者
	SendTime      int64                  `protobuf:"varint,4,opt,name=SendTime,proto3" json:"SendTime,omitempty"`       // 消息发送时间
	Content       string                 `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`          // 消息内容
	Number        int64                  `protobuf:"varint,6,opt,name=Number,proto3" json:"Number,omitempty"`           // 消息的编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageStruct) Reset() {
	*x = ChatMessageStruct{}
	mi := &file_Chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageStruct) ProtoMessage() {}

func (x *ChatMessageStruct) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageStruct.ProtoReflect.Descriptor instead.
func (*ChatMessageStruct) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessageStruct) GetSenderUID() int64 {
	if x != nil {
		return x.SenderUID
	}
	return 0
}

func (x *ChatMessageStruct) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMessageStruct) GetAccepterUID() int64 {
	if x != nil {
		return x.AccepterUID
	}
	return 0
}

func (x *ChatMessageStruct) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ChatMessageStruct) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageStruct) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

// 玩家收到新的消息推送结构
type ChatNewMessageStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   EChatChannelType       `protobuf:"varint,1,opt,name=ChannelType,proto3,enum=Chat.EChatChannelType" json:"ChannelType,omitempty"` // 消息类型
	ChannelID     string                 `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`                                 // 房间ID
	Messages      []*ChatMessageStruct   `protobuf:"bytes,3,rep,name=Messages,proto3" json:"Messages,omitempty"`                                   // 消息细节
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatNewMessageStruct) Reset() {
	*x = ChatNewMessageStruct{}
	mi := &file_Chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatNewMessageStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatNewMessageStruct) ProtoMessage() {}

func (x *ChatNewMessageStruct) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatNewMessageStruct.ProtoReflect.Descriptor instead.
func (*ChatNewMessageStruct) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatNewMessageStruct) GetChannelType() EChatChannelType {
	if x != nil {
		return x.ChannelType
	}
	return EChatChannelType_EChatCH_None
}

func (x *ChatNewMessageStruct) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *ChatNewMessageStruct) GetMessages() []*ChatMessageStruct {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 最近聊天记录
type ChatRecentStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordUID     int64                  `protobuf:"varint,1,opt,name=RecordUID,proto3" json:"RecordUID,omitempty"`  // 消息发送者
	RecordName    string                 `protobuf:"bytes,2,opt,name=RecordName,proto3" json:"RecordName,omitempty"` // 发送者名字
	SendTime      int64                  `protobuf:"varint,3,opt,name=SendTime,proto3" json:"SendTime,omitempty"`    // 消息发送时间
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`       // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRecentStruct) Reset() {
	*x = ChatRecentStruct{}
	mi := &file_Chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRecentStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRecentStruct) ProtoMessage() {}

func (x *ChatRecentStruct) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRecentStruct.ProtoReflect.Descriptor instead.
func (*ChatRecentStruct) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRecentStruct) GetRecordUID() int64 {
	if x != nil {
		return x.RecordUID
	}
	return 0
}

func (x *ChatRecentStruct) GetRecordName() string {
	if x != nil {
		return x.RecordName
	}
	return ""
}

func (x *ChatRecentStruct) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ChatRecentStruct) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ------------------------------------------------------------------
// c2s
// ------------------------------------------------------------------
// ------------------------------------------------------------------
// 请求: 发送聊天消息
// ------------------------------------------------------------------
type ReqChatSendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   EChatChannelType       `protobuf:"varint,1,opt,name=ChannelType,proto3,enum=Chat.EChatChannelType" json:"ChannelType,omitempty"` // 消息类型
	ChannelID     string                 `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`                                 // 房间ID
	AccepterUID   int64                  `protobuf:"varint,3,opt,name=AccepterUID,proto3" json:"AccepterUID,omitempty"`                            // 消息接受者(私聊使用单一频道需要)
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`                                     // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatSendMessage) Reset() {
	*x = ReqChatSendMessage{}
	mi := &file_Chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatSendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatSendMessage) ProtoMessage() {}

func (x *ReqChatSendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatSendMessage.ProtoReflect.Descriptor instead.
func (*ReqChatSendMessage) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{3}
}

func (x *ReqChatSendMessage) GetChannelType() EChatChannelType {
	if x != nil {
		return x.ChannelType
	}
	return EChatChannelType_EChatCH_None
}

func (x *ReqChatSendMessage) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *ReqChatSendMessage) GetAccepterUID() int64 {
	if x != nil {
		return x.AccepterUID
	}
	return 0
}

func (x *ReqChatSendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ------------------------------------------------------------------
// 请求: 获取历史消息
// ------------------------------------------------------------------
type ReqChatGetHistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   EChatChannelType       `protobuf:"varint,1,opt,name=ChannelType,proto3,enum=Chat.EChatChannelType" json:"ChannelType,omitempty"` // 消息类型
	ChannelID     string                 `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`                                 // 房间ID
	AccepterUID   int64                  `protobuf:"varint,3,opt,name=AccepterUID,proto3" json:"AccepterUID,omitempty"`                            // 私聊目标角色UID
	Cursor        int64                  `protobuf:"varint,4,opt,name=Cursor,proto3" json:"Cursor,omitempty"`                                      // 游标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatGetHistoryMessage) Reset() {
	*x = ReqChatGetHistoryMessage{}
	mi := &file_Chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatGetHistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatGetHistoryMessage) ProtoMessage() {}

func (x *ReqChatGetHistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatGetHistoryMessage.ProtoReflect.Descriptor instead.
func (*ReqChatGetHistoryMessage) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{4}
}

func (x *ReqChatGetHistoryMessage) GetChannelType() EChatChannelType {
	if x != nil {
		return x.ChannelType
	}
	return EChatChannelType_EChatCH_None
}

func (x *ReqChatGetHistoryMessage) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *ReqChatGetHistoryMessage) GetAccepterUID() int64 {
	if x != nil {
		return x.AccepterUID
	}
	return 0
}

func (x *ReqChatGetHistoryMessage) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

// ------------------------------------------------------------------
// 请求: 最近聊天列表
// ------------------------------------------------------------------
type ReqChatRecentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChatRecentList) Reset() {
	*x = ReqChatRecentList{}
	mi := &file_Chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChatRecentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChatRecentList) ProtoMessage() {}

func (x *ReqChatRecentList) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChatRecentList.ProtoReflect.Descriptor instead.
func (*ReqChatRecentList) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{5}
}

// ------------------------------------------------------------------
// s2c
// ------------------------------------------------------------------
// ------------------------------------------------------------------
// 推送: 收到消息
// ------------------------------------------------------------------
type RspChatReceiveMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	NewMessages   []*ChatNewMessageStruct `protobuf:"bytes,1,rep,name=NewMessages,proto3" json:"NewMessages,omitempty"` // 玩家收到的新消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatReceiveMessage) Reset() {
	*x = RspChatReceiveMessage{}
	mi := &file_Chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatReceiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatReceiveMessage) ProtoMessage() {}

func (x *RspChatReceiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatReceiveMessage.ProtoReflect.Descriptor instead.
func (*RspChatReceiveMessage) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{6}
}

func (x *RspChatReceiveMessage) GetNewMessages() []*ChatNewMessageStruct {
	if x != nil {
		return x.NewMessages
	}
	return nil
}

// ------------------------------------------------------------------
// 推送: 历史消息
// ------------------------------------------------------------------
type RspChatHistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   EChatChannelType       `protobuf:"varint,1,opt,name=ChannelType,proto3,enum=Chat.EChatChannelType" json:"ChannelType,omitempty"` // 消息类型
	ChannelID     string                 `protobuf:"bytes,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`                                 // 房间ID
	Cursor        int64                  `protobuf:"varint,3,opt,name=Cursor,proto3" json:"Cursor,omitempty"`                                      // 游标
	Messages      []*ChatMessageStruct   `protobuf:"bytes,4,rep,name=Messages,proto3" json:"Messages,omitempty"`                                   // 消息数组
	AccepterUID   int64                  `protobuf:"varint,5,opt,name=AccepterUID,proto3" json:"AccepterUID,omitempty"`                            // 玩家UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspChatHistoryMessage) Reset() {
	*x = RspChatHistoryMessage{}
	mi := &file_Chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatHistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatHistoryMessage) ProtoMessage() {}

func (x *RspChatHistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatHistoryMessage.ProtoReflect.Descriptor instead.
func (*RspChatHistoryMessage) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{7}
}

func (x *RspChatHistoryMessage) GetChannelType() EChatChannelType {
	if x != nil {
		return x.ChannelType
	}
	return EChatChannelType_EChatCH_None
}

func (x *RspChatHistoryMessage) GetChannelID() string {
	if x != nil {
		return x.ChannelID
	}
	return ""
}

func (x *RspChatHistoryMessage) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *RspChatHistoryMessage) GetMessages() []*ChatMessageStruct {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *RspChatHistoryMessage) GetAccepterUID() int64 {
	if x != nil {
		return x.AccepterUID
	}
	return 0
}

// ------------------------------------------------------------------
// 推送: 最近聊天列表
// ------------------------------------------------------------------
type RspChatRecentList struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	PrivateRecents map[string]*ChatRecentStruct `protobuf:"bytes,1,rep,name=PrivateRecents,proto3" json:"PrivateRecents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 好友最近聊天
	TeamRecents    map[string]*ChatRecentStruct `protobuf:"bytes,2,rep,name=TeamRecents,proto3" json:"TeamRecents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 队伍最近聊天记录
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RspChatRecentList) Reset() {
	*x = RspChatRecentList{}
	mi := &file_Chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspChatRecentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChatRecentList) ProtoMessage() {}

func (x *RspChatRecentList) ProtoReflect() protoreflect.Message {
	mi := &file_Chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChatRecentList.ProtoReflect.Descriptor instead.
func (*RspChatRecentList) Descriptor() ([]byte, []int) {
	return file_Chat_proto_rawDescGZIP(), []int{8}
}

func (x *RspChatRecentList) GetPrivateRecents() map[string]*ChatRecentStruct {
	if x != nil {
		return x.PrivateRecents
	}
	return nil
}

func (x *RspChatRecentList) GetTeamRecents() map[string]*ChatRecentStruct {
	if x != nil {
		return x.TeamRecents
	}
	return nil
}

var File_Chat_proto protoreflect.FileDescriptor

const file_Chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Chat.proto\x12\x04Chat\"\xc1\x01\n" +
	"\x11ChatMessageStruct\x12\x1c\n" +
	"\tSenderUID\x18\x01 \x01(\x03R\tSenderUID\x12\x1e\n" +
	"\n" +
	"SenderName\x18\x02 \x01(\tR\n" +
	"SenderName\x12 \n" +
	"\vAccepterUID\x18\x03 \x01(\x03R\vAccepterUID\x12\x1a\n" +
	"\bSendTime\x18\x04 \x01(\x03R\bSendTime\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent\x12\x16\n" +
	"\x06Number\x18\x06 \x01(\x03R\x06Number\"\xa3\x01\n" +
	"\x14ChatNewMessageStruct\x128\n" +
	"\vChannelType\x18\x01 \x01(\x0e2\x16.Chat.EChatChannelTypeR\vChannelType\x12\x1c\n" +
	"\tChannelID\x18\x02 \x01(\tR\tChannelID\x123\n" +
	"\bMessages\x18\x03 \x03(\v2\x17.Chat.ChatMessageStructR\bMessages\"\x86\x01\n" +
	"\x10ChatRecentStruct\x12\x1c\n" +
	"\tRecordUID\x18\x01 \x01(\x03R\tRecordUID\x12\x1e\n" +
	"\n" +
	"RecordName\x18\x02 \x01(\tR\n" +
	"RecordName\x12\x1a\n" +
	"\bSendTime\x18\x03 \x01(\x03R\bSendTime\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\"\xa8\x01\n" +
	"\x12ReqChatSendMessage\x128\n" +
	"\vChannelType\x18\x01 \x01(\x0e2\x16.Chat.EChatChannelTypeR\vChannelType\x12\x1c\n" +
	"\tChannelID\x18\x02 \x01(\tR\tChannelID\x12 \n" +
	"\vAccepterUID\x18\x03 \x01(\x03R\vAccepterUID\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\"\xac\x01\n" +
	"\x18ReqChatGetHistoryMessage\x128\n" +
	"\vChannelType\x18\x01 \x01(\x0e2\x16.Chat.EChatChannelTypeR\vChannelType\x12\x1c\n" +
	"\tChannelID\x18\x02 \x01(\tR\tChannelID\x12 \n" +
	"\vAccepterUID\x18\x03 \x01(\x03R\vAccepterUID\x12\x16\n" +
	"\x06Cursor\x18\x04 \x01(\x03R\x06Cursor\"\x13\n" +
	"\x11ReqChatRecentList\"U\n" +
	"\x15RspChatReceiveMessage\x12<\n" +
	"\vNewMessages\x18\x01 \x03(\v2\x1a.Chat.ChatNewMessageStructR\vNewMessages\"\xde\x01\n" +
	"\x15RspChatHistoryMessage\x128\n" +
	"\vChannelType\x18\x01 \x01(\x0e2\x16.Chat.EChatChannelTypeR\vChannelType\x12\x1c\n" +
	"\tChannelID\x18\x02 \x01(\tR\tChannelID\x12\x16\n" +
	"\x06Cursor\x18\x03 \x01(\x03R\x06Cursor\x123\n" +
	"\bMessages\x18\x04 \x03(\v2\x17.Chat.ChatMessageStructR\bMessages\x12 \n" +
	"\vAccepterUID\x18\x05 \x01(\x03R\vAccepterUID\"\xe7\x02\n" +
	"\x11RspChatRecentList\x12S\n" +
	"\x0ePrivateRecents\x18\x01 \x03(\v2+.Chat.RspChatRecentList.PrivateRecentsEntryR\x0ePrivateRecents\x12J\n" +
	"\vTeamRecents\x18\x02 \x03(\v2(.Chat.RspChatRecentList.TeamRecentsEntryR\vTeamRecents\x1aY\n" +
	"\x13PrivateRecentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.Chat.ChatRecentStructR\x05value:\x028\x01\x1aV\n" +
	"\x10TeamRecentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.Chat.ChatRecentStructR\x05value:\x028\x01*^\n" +
	"\x10EChatChannelType\x12\x10\n" +
	"\fEChatCH_None\x10\x00\x12\x11\n" +
	"\rEChatCH_World\x10\x01\x12\x10\n" +
	"\fEChatCH_Team\x10\x02\x12\x13\n" +
	"\x0fEChatCH_Private\x10\x03B2Z0github.com/zhanglifan/leaf_server/src/proto/Chatb\x06proto3"

var (
	file_Chat_proto_rawDescOnce sync.Once
	file_Chat_proto_rawDescData []byte
)

func file_Chat_proto_rawDescGZIP() []byte {
	file_Chat_proto_rawDescOnce.Do(func() {
		file_Chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Chat_proto_rawDesc), len(file_Chat_proto_rawDesc)))
	})
	return file_Chat_proto_rawDescData
}

var file_Chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Chat_proto_goTypes = []any{
	(EChatChannelType)(0),            // 0: Chat.EChatChannelType
	(*ChatMessageStruct)(nil),        // 1: Chat.ChatMessageStruct
	(*ChatNewMessageStruct)(nil),     // 2: Chat.ChatNewMessageStruct
	(*ChatRecentStruct)(nil),         // 3: Chat.ChatRecentStruct
	(*ReqChatSendMessage)(nil),       // 4: Chat.ReqChatSendMessage
	(*ReqChatGetHistoryMessage)(nil), // 5: Chat.ReqChatGetHistoryMessage
	(*ReqChatRecentList)(nil),        // 6: Chat.ReqChatRecentList
	(*RspChatReceiveMessage)(nil),    // 7: Chat.RspChatReceiveMessage
	(*RspChatHistoryMessage)(nil),    // 8: Chat.RspChatHistoryMessage
	(*RspChatRecentList)(nil),        // 9: Chat.RspChatRecentList
	nil,                              // 10: Chat.RspChatRecentList.PrivateRecentsEntry
	nil,                              // 11: Chat.RspChatRecentList.TeamRecentsEntry
}
var file_Chat_proto_depIdxs = []int32{
	0,  // 0: Chat.ChatNewMessageStruct.ChannelType:type_name -> Chat.EChatChannelType
	1,  // 1: Chat.ChatNewMessageStruct.Messages:type_name -> Chat.ChatMessageStruct
	0,  // 2: Chat.ReqChatSendMessage.ChannelType:type_name -> Chat.EChatChannelType
	0,  // 3: Chat.ReqChatGetHistoryMessage.ChannelType:type_name -> Chat.EChatChannelType
	2,  // 4: Chat.RspChatReceiveMessage.NewMessages:type_name -> Chat.ChatNewMessageStruct
	0,  // 5: Chat.RspChatHistoryMessage.ChannelType:type_name -> Chat.EChatChannelType
	1,  // 6: Chat.RspChatHistoryMessage.Messages:type_name -> Chat.ChatMessageStruct
	10, // 7: Chat.RspChatRecentList.PrivateRecents:type_name -> Chat.RspChatRecentList.PrivateRecentsEntry
	11, // 8: Chat.RspChatRecentList.TeamRecents:type_name -> Chat.RspChatRecentList.TeamRecentsEntry
	3,  // 9: Chat.RspChatRecentList.PrivateRecentsEntry.value:type_name -> Chat.ChatRecentStruct
	3,  // 10: Chat.RspChatRecentList.TeamRecentsEntry.value:type_name -> Chat.ChatRecentStruct
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_Chat_proto_init() }
func file_Chat_proto_init() {
	if File_Chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Chat_proto_rawDesc), len(file_Chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Chat_proto_goTypes,
		DependencyIndexes: file_Chat_proto_depIdxs,
		EnumInfos:         file_Chat_proto_enumTypes,
		MessageInfos:      file_Chat_proto_msgTypes,
	}.Build()
	File_Chat_proto = out.File
	file_Chat_proto_goTypes = nil
	file_Chat_proto_depIdxs = nil
}
