// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: Level.proto

package Level

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------------------------------------
// 请求：上报服务器信息
type ReqUploadServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddr    string                 `protobuf:"bytes,1,opt,name=ServerAddr,proto3" json:"ServerAddr,omitempty"`        // 服务器地址 Session
	ServerUID     int64                  `protobuf:"varint,2,opt,name=ServerUID,proto3" json:"ServerUID,omitempty"`         // 服务器 UID
	LaunchSucceed bool                   `protobuf:"varint,3,opt,name=LaunchSucceed,proto3" json:"LaunchSucceed,omitempty"` // 服务器启动成功
	ServerPasswd  string                 `protobuf:"bytes,4,opt,name=ServerPasswd,proto3" json:"ServerPasswd,omitempty"`    // 服务器密码：只有持有此密码的匹配客户端才能加入
	MapID         int32                  `protobuf:"varint,5,opt,name=MapID,proto3" json:"MapID,omitempty"`                 // 地图 ID
	ErrorCodeID   int32                  `protobuf:"varint,6,opt,name=ErrorCodeID,proto3" json:"ErrorCodeID,omitempty"`     // 错误码 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUploadServerInfo) Reset() {
	*x = ReqUploadServerInfo{}
	mi := &file_Level_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUploadServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUploadServerInfo) ProtoMessage() {}

func (x *ReqUploadServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUploadServerInfo.ProtoReflect.Descriptor instead.
func (*ReqUploadServerInfo) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUploadServerInfo) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *ReqUploadServerInfo) GetServerUID() int64 {
	if x != nil {
		return x.ServerUID
	}
	return 0
}

func (x *ReqUploadServerInfo) GetLaunchSucceed() bool {
	if x != nil {
		return x.LaunchSucceed
	}
	return false
}

func (x *ReqUploadServerInfo) GetServerPasswd() string {
	if x != nil {
		return x.ServerPasswd
	}
	return ""
}

func (x *ReqUploadServerInfo) GetMapID() int32 {
	if x != nil {
		return x.MapID
	}
	return 0
}

func (x *ReqUploadServerInfo) GetErrorCodeID() int32 {
	if x != nil {
		return x.ErrorCodeID
	}
	return 0
}

// 响应: 服务器ServerUID
type RspServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUID     int64                  `protobuf:"varint,1,opt,name=ServerUID,proto3" json:"ServerUID,omitempty"` // 服务器 UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspServerInfo) Reset() {
	*x = RspServerInfo{}
	mi := &file_Level_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspServerInfo) ProtoMessage() {}

func (x *RspServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspServerInfo.ProtoReflect.Descriptor instead.
func (*RspServerInfo) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{1}
}

func (x *RspServerInfo) GetServerUID() int64 {
	if x != nil {
		return x.ServerUID
	}
	return 0
}

// ------------------------------------------------------------------
// 数据：对局开始时玩家数据
type LevelPlayerData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountID        string                 `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`                                                                                            // 账号 ID
	RoleUID          int64                  `protobuf:"varint,2,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`                                                                                               // 角色 UID
	RoleName         string                 `protobuf:"bytes,3,opt,name=RoleName,proto3" json:"RoleName,omitempty"`                                                                                              // 角色名称
	GenderType       int32                  `protobuf:"varint,4,opt,name=GenderType,proto3" json:"GenderType,omitempty"`                                                                                         // 性别
	CustomModelIDs   map[int32]int32        `protobuf:"bytes,5,rep,name=CustomModelIDs,proto3" json:"CustomModelIDs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`      // 自定义模型ID(部位+对应ID)
	CustomColorIDs   map[int32]int32        `protobuf:"bytes,6,rep,name=CustomColorIDs,proto3" json:"CustomColorIDs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`      // 自定义颜色ID(部位+对应ID)
	RoleLevel        int32                  `protobuf:"varint,7,opt,name=RoleLevel,proto3" json:"RoleLevel,omitempty"`                                                                                           // 角色等级
	JobNumber        string                 `protobuf:"bytes,8,opt,name=JobNumber,proto3" json:"JobNumber,omitempty"`                                                                                            // 工号
	TeamID           int32                  `protobuf:"varint,10,opt,name=TeamID,proto3" json:"TeamID,omitempty"`                                                                                                // 队伍 ID (>=1)
	LevelToken       string                 `protobuf:"bytes,11,opt,name=LevelToken,proto3" json:"LevelToken,omitempty"`                                                                                         // 令牌: 用作连接验证
	HeroCfgID        int32                  `protobuf:"varint,12,opt,name=HeroCfgID,proto3" json:"HeroCfgID,omitempty"`                                                                                          // 英雄 ID
	CurWeaponList    map[int32]int32        `protobuf:"bytes,20,rep,name=CurWeaponList,proto3" json:"CurWeaponList,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`       // 当前使用的武器(武器槽+对应武器ID) : 最大数量 5
	CurEquipmentList map[int32]int32        `protobuf:"bytes,21,rep,name=CurEquipmentList,proto3" json:"CurEquipmentList,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 当前使用的防具(防具槽+对应防具ID) ： 最大数量 5
	CurSkillList     map[int32]int32        `protobuf:"bytes,30,rep,name=CurSkillList,proto3" json:"CurSkillList,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`         // 快捷键：当前使用的技能列表(绑定Key+对应技能ID) ： 最大数量 255
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LevelPlayerData) Reset() {
	*x = LevelPlayerData{}
	mi := &file_Level_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelPlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelPlayerData) ProtoMessage() {}

func (x *LevelPlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelPlayerData.ProtoReflect.Descriptor instead.
func (*LevelPlayerData) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{2}
}

func (x *LevelPlayerData) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *LevelPlayerData) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

func (x *LevelPlayerData) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *LevelPlayerData) GetGenderType() int32 {
	if x != nil {
		return x.GenderType
	}
	return 0
}

func (x *LevelPlayerData) GetCustomModelIDs() map[int32]int32 {
	if x != nil {
		return x.CustomModelIDs
	}
	return nil
}

func (x *LevelPlayerData) GetCustomColorIDs() map[int32]int32 {
	if x != nil {
		return x.CustomColorIDs
	}
	return nil
}

func (x *LevelPlayerData) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *LevelPlayerData) GetJobNumber() string {
	if x != nil {
		return x.JobNumber
	}
	return ""
}

func (x *LevelPlayerData) GetTeamID() int32 {
	if x != nil {
		return x.TeamID
	}
	return 0
}

func (x *LevelPlayerData) GetLevelToken() string {
	if x != nil {
		return x.LevelToken
	}
	return ""
}

func (x *LevelPlayerData) GetHeroCfgID() int32 {
	if x != nil {
		return x.HeroCfgID
	}
	return 0
}

func (x *LevelPlayerData) GetCurWeaponList() map[int32]int32 {
	if x != nil {
		return x.CurWeaponList
	}
	return nil
}

func (x *LevelPlayerData) GetCurEquipmentList() map[int32]int32 {
	if x != nil {
		return x.CurEquipmentList
	}
	return nil
}

func (x *LevelPlayerData) GetCurSkillList() map[int32]int32 {
	if x != nil {
		return x.CurSkillList
	}
	return nil
}

// 反馈：匹配服发送玩家数据，对局开始
type RspStartLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerList    []*LevelPlayerData     `protobuf:"bytes,1,rep,name=PlayerList,proto3" json:"PlayerList,omitempty"` // 玩家列表
	FillRobot     bool                   `protobuf:"varint,2,opt,name=FillRobot,proto3" json:"FillRobot,omitempty"`  // 是否自行补充机器人
	LevelUID      string                 `protobuf:"bytes,3,opt,name=LevelUID,proto3" json:"LevelUID,omitempty"`     // 对局标识 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspStartLevel) Reset() {
	*x = RspStartLevel{}
	mi := &file_Level_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspStartLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspStartLevel) ProtoMessage() {}

func (x *RspStartLevel) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspStartLevel.ProtoReflect.Descriptor instead.
func (*RspStartLevel) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{3}
}

func (x *RspStartLevel) GetPlayerList() []*LevelPlayerData {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *RspStartLevel) GetFillRobot() bool {
	if x != nil {
		return x.FillRobot
	}
	return false
}

func (x *RspStartLevel) GetLevelUID() string {
	if x != nil {
		return x.LevelUID
	}
	return ""
}

// 请求：对局初始化完成后，发送确认包 【之后才会通知玩家加入对局】
type ReqInitedLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`         // 是否成功
	ErrorCodeID   int32                  `protobuf:"varint,2,opt,name=ErrorCodeID,proto3" json:"ErrorCodeID,omitempty"` // 错误码 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqInitedLevel) Reset() {
	*x = ReqInitedLevel{}
	mi := &file_Level_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqInitedLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqInitedLevel) ProtoMessage() {}

func (x *ReqInitedLevel) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqInitedLevel.ProtoReflect.Descriptor instead.
func (*ReqInitedLevel) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{4}
}

func (x *ReqInitedLevel) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *ReqInitedLevel) GetErrorCodeID() int32 {
	if x != nil {
		return x.ErrorCodeID
	}
	return 0
}

// ------------------------------------------------------------------
// 请求：通知-玩家进入对局
type ReqPlayerEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleUID       int64                  `protobuf:"varint,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"` // 角色 UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPlayerEnter) Reset() {
	*x = ReqPlayerEnter{}
	mi := &file_Level_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPlayerEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlayerEnter) ProtoMessage() {}

func (x *ReqPlayerEnter) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlayerEnter.ProtoReflect.Descriptor instead.
func (*ReqPlayerEnter) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{5}
}

func (x *ReqPlayerEnter) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

// 请求：通知-玩家离开对局（正常、异常情况）
type ReqPlayerExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleUID       int64                  `protobuf:"varint,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`           // 角色 UID
	IsNormalExit  bool                   `protobuf:"varint,2,opt,name=IsNormalExit,proto3" json:"IsNormalExit,omitempty"` // 是否正常退出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPlayerExit) Reset() {
	*x = ReqPlayerExit{}
	mi := &file_Level_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPlayerExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlayerExit) ProtoMessage() {}

func (x *ReqPlayerExit) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlayerExit.ProtoReflect.Descriptor instead.
func (*ReqPlayerExit) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{6}
}

func (x *ReqPlayerExit) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

func (x *ReqPlayerExit) GetIsNormalExit() bool {
	if x != nil {
		return x.IsNormalExit
	}
	return false
}

// ------------------------------------------------------------------
// 反馈：询问-某个玩家是否可以断线重连
type QueryPlayerCanConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleUID       int64                  `protobuf:"varint,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"` // 角色 UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPlayerCanConnect) Reset() {
	*x = QueryPlayerCanConnect{}
	mi := &file_Level_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPlayerCanConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlayerCanConnect) ProtoMessage() {}

func (x *QueryPlayerCanConnect) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlayerCanConnect.ProtoReflect.Descriptor instead.
func (*QueryPlayerCanConnect) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{7}
}

func (x *QueryPlayerCanConnect) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

// 请求：上报-某个玩家是否可以断线重连
type ReportPlayerCanConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleUID       int64                  `protobuf:"varint,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`       // 角色 UID
	CanConnect    bool                   `protobuf:"varint,2,opt,name=CanConnect,proto3" json:"CanConnect,omitempty"` // 是否可以重连
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPlayerCanConnect) Reset() {
	*x = ReportPlayerCanConnect{}
	mi := &file_Level_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPlayerCanConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPlayerCanConnect) ProtoMessage() {}

func (x *ReportPlayerCanConnect) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPlayerCanConnect.ProtoReflect.Descriptor instead.
func (*ReportPlayerCanConnect) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{8}
}

func (x *ReportPlayerCanConnect) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

func (x *ReportPlayerCanConnect) GetCanConnect() bool {
	if x != nil {
		return x.CanConnect
	}
	return false
}

// ------------------------------------------------------------------
// 数据：对局结束时玩家数据
type PlayerLevelEndData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoleUID             int64                  `protobuf:"varint,1,opt,name=RoleUID,proto3" json:"RoleUID,omitempty"`                          // 角色 UID
	IsWin               bool                   `protobuf:"varint,2,opt,name=IsWin,proto3" json:"IsWin,omitempty"`                              // 是否胜利  【废弃】
	HeroCfgID           int32                  `protobuf:"varint,10,opt,name=HeroCfgID,proto3" json:"HeroCfgID,omitempty"`                     // 英雄 ID
	Rank                int32                  `protobuf:"varint,11,opt,name=Rank,proto3" json:"Rank,omitempty"`                               // 排名
	Kills               int32                  `protobuf:"varint,12,opt,name=Kills,proto3" json:"Kills,omitempty"`                             // 击杀数
	TotalHurt           int64                  `protobuf:"varint,13,opt,name=TotalHurt,proto3" json:"TotalHurt,omitempty"`                     // 本局造成的总伤害
	Deaths              int32                  `protobuf:"varint,14,opt,name=Deaths,proto3" json:"Deaths,omitempty"`                           // 本局死亡次数（包括一阶段与二阶段）
	Heals               int32                  `protobuf:"varint,15,opt,name=Heals,proto3" json:"Heals,omitempty"`                             // 本局治疗自己或队友的数值
	BuildComponentCount int32                  `protobuf:"varint,16,opt,name=BuildComponentCount,proto3" json:"BuildComponentCount,omitempty"` // 本局获取的build组件数量
	KillsMonsterSimple  int32                  `protobuf:"varint,17,opt,name=KillsMonsterSimple,proto3" json:"KillsMonsterSimple,omitempty"`   // 本局击杀的小怪总数
	KillsMonsterElite   int32                  `protobuf:"varint,18,opt,name=KillsMonsterElite,proto3" json:"KillsMonsterElite,omitempty"`     // 本局击杀的精英怪总数
	PhaseOneAreaCount   int32                  `protobuf:"varint,19,opt,name=PhaseOneAreaCount,proto3" json:"PhaseOneAreaCount,omitempty"`     // 本局在一阶段中完成的区域数量
	RelicObtained       bool                   `protobuf:"varint,20,opt,name=RelicObtained,proto3" json:"RelicObtained,omitempty"`             // 本局是否拾取过圣物
	RelicHoldDuration   int32                  `protobuf:"varint,21,opt,name=RelicHoldDuration,proto3" json:"RelicHoldDuration,omitempty"`     // 本局持有圣物的时长
	BuildSkillCount     int32                  `protobuf:"varint,22,opt,name=BuildSkillCount,proto3" json:"BuildSkillCount,omitempty"`         // 本局凑出的技能数量
	Score               int32                  `protobuf:"varint,23,opt,name=Score,proto3" json:"Score,omitempty"`                             // 赛季得分（排位分）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerLevelEndData) Reset() {
	*x = PlayerLevelEndData{}
	mi := &file_Level_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLevelEndData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLevelEndData) ProtoMessage() {}

func (x *PlayerLevelEndData) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLevelEndData.ProtoReflect.Descriptor instead.
func (*PlayerLevelEndData) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerLevelEndData) GetRoleUID() int64 {
	if x != nil {
		return x.RoleUID
	}
	return 0
}

func (x *PlayerLevelEndData) GetIsWin() bool {
	if x != nil {
		return x.IsWin
	}
	return false
}

func (x *PlayerLevelEndData) GetHeroCfgID() int32 {
	if x != nil {
		return x.HeroCfgID
	}
	return 0
}

func (x *PlayerLevelEndData) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PlayerLevelEndData) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerLevelEndData) GetTotalHurt() int64 {
	if x != nil {
		return x.TotalHurt
	}
	return 0
}

func (x *PlayerLevelEndData) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerLevelEndData) GetHeals() int32 {
	if x != nil {
		return x.Heals
	}
	return 0
}

func (x *PlayerLevelEndData) GetBuildComponentCount() int32 {
	if x != nil {
		return x.BuildComponentCount
	}
	return 0
}

func (x *PlayerLevelEndData) GetKillsMonsterSimple() int32 {
	if x != nil {
		return x.KillsMonsterSimple
	}
	return 0
}

func (x *PlayerLevelEndData) GetKillsMonsterElite() int32 {
	if x != nil {
		return x.KillsMonsterElite
	}
	return 0
}

func (x *PlayerLevelEndData) GetPhaseOneAreaCount() int32 {
	if x != nil {
		return x.PhaseOneAreaCount
	}
	return 0
}

func (x *PlayerLevelEndData) GetRelicObtained() bool {
	if x != nil {
		return x.RelicObtained
	}
	return false
}

func (x *PlayerLevelEndData) GetRelicHoldDuration() int32 {
	if x != nil {
		return x.RelicHoldDuration
	}
	return 0
}

func (x *PlayerLevelEndData) GetBuildSkillCount() int32 {
	if x != nil {
		return x.BuildSkillCount
	}
	return 0
}

func (x *PlayerLevelEndData) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 请求：对局结束后，发送结果给后端
type ReqFinishLevel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerList     []*PlayerLevelEndData  `protobuf:"bytes,1,rep,name=PlayerList,proto3" json:"PlayerList,omitempty"`          // 玩家列表
	LevelTimeStart int32                  `protobuf:"varint,2,opt,name=LevelTimeStart,proto3" json:"LevelTimeStart,omitempty"` // 比赛开始时间
	LevelTimeEnd   int32                  `protobuf:"varint,3,opt,name=LevelTimeEnd,proto3" json:"LevelTimeEnd,omitempty"`     // 比赛结束时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReqFinishLevel) Reset() {
	*x = ReqFinishLevel{}
	mi := &file_Level_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFinishLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFinishLevel) ProtoMessage() {}

func (x *ReqFinishLevel) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFinishLevel.ProtoReflect.Descriptor instead.
func (*ReqFinishLevel) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{10}
}

func (x *ReqFinishLevel) GetPlayerList() []*PlayerLevelEndData {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *ReqFinishLevel) GetLevelTimeStart() int32 {
	if x != nil {
		return x.LevelTimeStart
	}
	return 0
}

func (x *ReqFinishLevel) GetLevelTimeEnd() int32 {
	if x != nil {
		return x.LevelTimeEnd
	}
	return 0
}

// 反馈：对局结束结果。 若错误码为 0 才可退出进程，否则打印错误、并重试 ReqFinishLevel。
type RspFinishLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCodeID   int32                  `protobuf:"varint,1,opt,name=ErrorCodeID,proto3" json:"ErrorCodeID,omitempty"` // 错误码 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspFinishLevel) Reset() {
	*x = RspFinishLevel{}
	mi := &file_Level_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspFinishLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspFinishLevel) ProtoMessage() {}

func (x *RspFinishLevel) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspFinishLevel.ProtoReflect.Descriptor instead.
func (*RspFinishLevel) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{11}
}

func (x *RspFinishLevel) GetErrorCodeID() int32 {
	if x != nil {
		return x.ErrorCodeID
	}
	return 0
}

var File_Level_proto protoreflect.FileDescriptor

const file_Level_proto_rawDesc = "" +
	"\n" +
	"\vLevel.proto\x12\x05Level\"\xd5\x01\n" +
	"\x13ReqUploadServerInfo\x12\x1e\n" +
	"\n" +
	"ServerAddr\x18\x01 \x01(\tR\n" +
	"ServerAddr\x12\x1c\n" +
	"\tServerUID\x18\x02 \x01(\x03R\tServerUID\x12$\n" +
	"\rLaunchSucceed\x18\x03 \x01(\bR\rLaunchSucceed\x12\"\n" +
	"\fServerPasswd\x18\x04 \x01(\tR\fServerPasswd\x12\x14\n" +
	"\x05MapID\x18\x05 \x01(\x05R\x05MapID\x12 \n" +
	"\vErrorCodeID\x18\x06 \x01(\x05R\vErrorCodeID\"-\n" +
	"\rRspServerInfo\x12\x1c\n" +
	"\tServerUID\x18\x01 \x01(\x03R\tServerUID\"\x86\b\n" +
	"\x0fLevelPlayerData\x12\x1c\n" +
	"\tAccountID\x18\x01 \x01(\tR\tAccountID\x12\x18\n" +
	"\aRoleUID\x18\x02 \x01(\x03R\aRoleUID\x12\x1a\n" +
	"\bRoleName\x18\x03 \x01(\tR\bRoleName\x12\x1e\n" +
	"\n" +
	"GenderType\x18\x04 \x01(\x05R\n" +
	"GenderType\x12R\n" +
	"\x0eCustomModelIDs\x18\x05 \x03(\v2*.Level.LevelPlayerData.CustomModelIDsEntryR\x0eCustomModelIDs\x12R\n" +
	"\x0eCustomColorIDs\x18\x06 \x03(\v2*.Level.LevelPlayerData.CustomColorIDsEntryR\x0eCustomColorIDs\x12\x1c\n" +
	"\tRoleLevel\x18\a \x01(\x05R\tRoleLevel\x12\x1c\n" +
	"\tJobNumber\x18\b \x01(\tR\tJobNumber\x12\x16\n" +
	"\x06TeamID\x18\n" +
	" \x01(\x05R\x06TeamID\x12\x1e\n" +
	"\n" +
	"LevelToken\x18\v \x01(\tR\n" +
	"LevelToken\x12\x1c\n" +
	"\tHeroCfgID\x18\f \x01(\x05R\tHeroCfgID\x12O\n" +
	"\rCurWeaponList\x18\x14 \x03(\v2).Level.LevelPlayerData.CurWeaponListEntryR\rCurWeaponList\x12X\n" +
	"\x10CurEquipmentList\x18\x15 \x03(\v2,.Level.LevelPlayerData.CurEquipmentListEntryR\x10CurEquipmentList\x12L\n" +
	"\fCurSkillList\x18\x1e \x03(\v2(.Level.LevelPlayerData.CurSkillListEntryR\fCurSkillList\x1aA\n" +
	"\x13CustomModelIDsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13CustomColorIDsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\n" +
	"\x12CurWeaponListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15CurEquipmentListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11CurSkillListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x81\x01\n" +
	"\rRspStartLevel\x126\n" +
	"\n" +
	"PlayerList\x18\x01 \x03(\v2\x16.Level.LevelPlayerDataR\n" +
	"PlayerList\x12\x1c\n" +
	"\tFillRobot\x18\x02 \x01(\bR\tFillRobot\x12\x1a\n" +
	"\bLevelUID\x18\x03 \x01(\tR\bLevelUID\"L\n" +
	"\x0eReqInitedLevel\x12\x18\n" +
	"\aSucceed\x18\x01 \x01(\bR\aSucceed\x12 \n" +
	"\vErrorCodeID\x18\x02 \x01(\x05R\vErrorCodeID\"*\n" +
	"\x0eReqPlayerEnter\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\x03R\aRoleUID\"M\n" +
	"\rReqPlayerExit\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\x03R\aRoleUID\x12\"\n" +
	"\fIsNormalExit\x18\x02 \x01(\bR\fIsNormalExit\"1\n" +
	"\x15QueryPlayerCanConnect\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\x03R\aRoleUID\"R\n" +
	"\x16ReportPlayerCanConnect\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\x03R\aRoleUID\x12\x1e\n" +
	"\n" +
	"CanConnect\x18\x02 \x01(\bR\n" +
	"CanConnect\"\xaa\x04\n" +
	"\x12PlayerLevelEndData\x12\x18\n" +
	"\aRoleUID\x18\x01 \x01(\x03R\aRoleUID\x12\x14\n" +
	"\x05IsWin\x18\x02 \x01(\bR\x05IsWin\x12\x1c\n" +
	"\tHeroCfgID\x18\n" +
	" \x01(\x05R\tHeroCfgID\x12\x12\n" +
	"\x04Rank\x18\v \x01(\x05R\x04Rank\x12\x14\n" +
	"\x05Kills\x18\f \x01(\x05R\x05Kills\x12\x1c\n" +
	"\tTotalHurt\x18\r \x01(\x03R\tTotalHurt\x12\x16\n" +
	"\x06Deaths\x18\x0e \x01(\x05R\x06Deaths\x12\x14\n" +
	"\x05Heals\x18\x0f \x01(\x05R\x05Heals\x120\n" +
	"\x13BuildComponentCount\x18\x10 \x01(\x05R\x13BuildComponentCount\x12.\n" +
	"\x12KillsMonsterSimple\x18\x11 \x01(\x05R\x12KillsMonsterSimple\x12,\n" +
	"\x11KillsMonsterElite\x18\x12 \x01(\x05R\x11KillsMonsterElite\x12,\n" +
	"\x11PhaseOneAreaCount\x18\x13 \x01(\x05R\x11PhaseOneAreaCount\x12$\n" +
	"\rRelicObtained\x18\x14 \x01(\bR\rRelicObtained\x12,\n" +
	"\x11RelicHoldDuration\x18\x15 \x01(\x05R\x11RelicHoldDuration\x12(\n" +
	"\x0fBuildSkillCount\x18\x16 \x01(\x05R\x0fBuildSkillCount\x12\x14\n" +
	"\x05Score\x18\x17 \x01(\x05R\x05Score\"\x97\x01\n" +
	"\x0eReqFinishLevel\x129\n" +
	"\n" +
	"PlayerList\x18\x01 \x03(\v2\x19.Level.PlayerLevelEndDataR\n" +
	"PlayerList\x12&\n" +
	"\x0eLevelTimeStart\x18\x02 \x01(\x05R\x0eLevelTimeStart\x12\"\n" +
	"\fLevelTimeEnd\x18\x03 \x01(\x05R\fLevelTimeEnd\"2\n" +
	"\x0eRspFinishLevel\x12 \n" +
	"\vErrorCodeID\x18\x01 \x01(\x05R\vErrorCodeIDB3Z1github.com/zhanglifan/leaf_server/src/proto/Levelb\x06proto3"

var (
	file_Level_proto_rawDescOnce sync.Once
	file_Level_proto_rawDescData []byte
)

func file_Level_proto_rawDescGZIP() []byte {
	file_Level_proto_rawDescOnce.Do(func() {
		file_Level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Level_proto_rawDesc), len(file_Level_proto_rawDesc)))
	})
	return file_Level_proto_rawDescData
}

var file_Level_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_Level_proto_goTypes = []any{
	(*ReqUploadServerInfo)(nil),    // 0: Level.ReqUploadServerInfo
	(*RspServerInfo)(nil),          // 1: Level.RspServerInfo
	(*LevelPlayerData)(nil),        // 2: Level.LevelPlayerData
	(*RspStartLevel)(nil),          // 3: Level.RspStartLevel
	(*ReqInitedLevel)(nil),         // 4: Level.ReqInitedLevel
	(*ReqPlayerEnter)(nil),         // 5: Level.ReqPlayerEnter
	(*ReqPlayerExit)(nil),          // 6: Level.ReqPlayerExit
	(*QueryPlayerCanConnect)(nil),  // 7: Level.QueryPlayerCanConnect
	(*ReportPlayerCanConnect)(nil), // 8: Level.ReportPlayerCanConnect
	(*PlayerLevelEndData)(nil),     // 9: Level.PlayerLevelEndData
	(*ReqFinishLevel)(nil),         // 10: Level.ReqFinishLevel
	(*RspFinishLevel)(nil),         // 11: Level.RspFinishLevel
	nil,                            // 12: Level.LevelPlayerData.CustomModelIDsEntry
	nil,                            // 13: Level.LevelPlayerData.CustomColorIDsEntry
	nil,                            // 14: Level.LevelPlayerData.CurWeaponListEntry
	nil,                            // 15: Level.LevelPlayerData.CurEquipmentListEntry
	nil,                            // 16: Level.LevelPlayerData.CurSkillListEntry
}
var file_Level_proto_depIdxs = []int32{
	12, // 0: Level.LevelPlayerData.CustomModelIDs:type_name -> Level.LevelPlayerData.CustomModelIDsEntry
	13, // 1: Level.LevelPlayerData.CustomColorIDs:type_name -> Level.LevelPlayerData.CustomColorIDsEntry
	14, // 2: Level.LevelPlayerData.CurWeaponList:type_name -> Level.LevelPlayerData.CurWeaponListEntry
	15, // 3: Level.LevelPlayerData.CurEquipmentList:type_name -> Level.LevelPlayerData.CurEquipmentListEntry
	16, // 4: Level.LevelPlayerData.CurSkillList:type_name -> Level.LevelPlayerData.CurSkillListEntry
	2,  // 5: Level.RspStartLevel.PlayerList:type_name -> Level.LevelPlayerData
	9,  // 6: Level.ReqFinishLevel.PlayerList:type_name -> Level.PlayerLevelEndData
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_Level_proto_init() }
func file_Level_proto_init() {
	if File_Level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Level_proto_rawDesc), len(file_Level_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Level_proto_goTypes,
		DependencyIndexes: file_Level_proto_depIdxs,
		MessageInfos:      file_Level_proto_msgTypes,
	}.Build()
	File_Level_proto = out.File
	file_Level_proto_goTypes = nil
	file_Level_proto_depIdxs = nil
}
